---

# - name: ping
#   hosts: jails
#   tasks:
#     - ping:
- name: Install nginx
  hosts: jails
  become: yes
  tasks:
    - pkgng:
       name: nginx
       state: present
    - service:
       name: nginx
       enabled: yes
       state: started

